services:

  rapids-notebook:
    image: rapidsai/notebooks:23.12a-cuda12.0-py3.9
    container_name: rapids-notebook
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8889:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  

  

  