

services:
  postgres-application:
    container_name: postgres-application
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - C:/Users/luizh/Desktop/lab/postgres-application:/var/lib/postgres/data'
    restart: unless-stopped

  
  

  

  