version: '3'

services:
  jupyter:
    container_name: jupyter
    build: images/jupyter/.
    user: root
    environment:
      PYTHON_VERSION: 3.9.18
      JUPYTER_TOKEN: "senha"
      NB_USER: "user"
      CHOWN_HOME: "yes"
      CHOWN_EXTRA_OPTS: "-R"
    ports:
      - 8888:8888
    volumes:
      - ${BASE_PATH}/data/jupyter:/home/user/work
    working_dir: /home/user/
    restart: unless-stopped

  spark-master: 
    container_name: spark-master
    image: bitnami/spark:3.4.1
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: null
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    ports:
      - 7077:7077
      - 4040:8080
      - 6066:6066
    volumes:
      - ${BASE_PATH}/data/spark/conf:/opt/bitnami/spark/conf
    restart: unless-stopped

  spark-worker-0:
    container_name: spark-worker-0
    image: bitnami/spark:3.4.1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_CORES: 12
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    ports:
      - 4041:8081
    volumes:
      - ${BASE_PATH}/data/spark/conf:/opt/bitnami/spark/conf
    restart: unless-stopped

  rapids-notebook:
    image: rapidsai/notebooks:23.12a-cuda12.0-py3.9
    container_name: rapids-notebook
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8889:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  default:
    name: spark_lab