version: '3'

services:
  postgres-hive-metastore:
    container_name: postgres-hive-metastore
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metastore_db
      PGDATA: /data/postgres
    ports:
      - 9032:5432
    volumes:
      - C:/Users/luizh/Documents/GitHub/spark-lab/postgres-hive-metastore:/data/postgres